# Generated by Django 5.2.7 on 2025-11-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_like_count_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
